[[sec:havingaball]]
=== Having a ball with tdd

:testsourcedir: {topics}/solution/olifantysballs/src/test/

// Working through this project gave me some new insights and made me realize that
// there is much sense in demonstrating things to students.

The exercise is about:

* implementing a state machine using the https://en.wikipedia.org/wiki/State_pattern[GoF State Pattern ^].
** `ejectCoin(...)`,
** `refill(...)`
** and `draw(...)` +
    which can be understood as events, modelled in the interface `State` and should
    therefore have an implementation in each state.
* and four states:
** `SOLD_OUT`,
** `NO_COIN`,
** `HAS_COIN`
** and `WINNER`.
* The initial project has some issues, design wise, but we will address them later.

// Study the <<state_diagram>> below.

[[state_diagram]]
.state diagram of the gumball machine.
image::statemachine.svg[State machine]


Study the state diagram, it is the (whole) specification of the first SUT.

We will start testing the state class. As we have chosen to implement the states
using an `enum`, called `StateEnum` in this design, implementing the `State` interface.

The relation between the context and it's states, designed according to the
https://en.wikipedia.org/wiki/Design_Patterns[GoF^] design pattern https://en.wikipedia.org/wiki/State_pattern[State ^].
[[context]]
.context in the state machine
image::{topics}/images/context.svg[Context]

Because both the Java artefacts `Context` and `State` in the initial design are
interfaces, we've added the UML `public` visibility modifier to all methods,
because that is how interfaces work in Java.

A traditional way to present state and state machine is a state transition table.
This technique predates UML, but is still valuable, in particular because it will
list all possibilities and thus will help to find more test cases,
ensuring that the set of tests is complete.

In the table below, `[empty]` and `[WINNER]` are guard expressions, with the outcome specified for the moment of evaluation.
Where there is no value in the guard columns, the guard is not relevant. For the column *End State*, empty means no state change.
[[StateTable]]

[format="csv", options="header,small"]
|===
include::solution/olifantysballs/src/test/resources/olifantysballs/testtable.csv[]
|===

The table reiterates that the state `HAS_COIN` needs the most attention in testing. +
Also note that this table is just the specification, just like the state diagram,
and not the implementation.

==== Lets start coding

...err, writing our tests.
To get our `State` tested without any real machine nearby, we must mock out `Context`.
This can be done by hand, but would soon make us create a context implementation that sort of works, but

 * first of all, is not tested itself, thus violates the TDD workflow
 * does not behave the way we need it in the test for the `State` type
 * and we do not need to have this context to behave in any way other
 then to give predictable answers when called by the State, and we must
 ensure that the State has the exact interactions we want. Not too few, and also not too many.

This is where http://mockito.org[Mockito ^] comes in. We only use a few of its features, namely

  * the mocking facility,
  * recording and playback of method calls and return values
  * verification of the correct calls on the mocked Context.

Our setup looks as follows:

[[Mock-setup]]
.preparing for tests: setup.
[source,java]
----
include::{testsourcedir}/olifantysballs/StateEnumTest.java[lines=23..33]
----

<1> The annotation makes Mockito insert a mocked context, that is a class that
can be controlled in our tests.
<2> Is the type and name of the mock.
<3> Creates a `StringOutput` and
<4> ensure that anything output by the context is returned in an easily
interpreted `String`. Also, every test is executed between a `setup()` and
`teardown` call, if available (In Junit 4, annotated with `@Before` and
`@After`). This makes inspection of the output easier.
<5> Sets the Mockito annotations to do their thing and
<6> lets the machine return our
crafted `out` when it calls for it's `PrintStream`.

This basic setup is done for every test anew and makes sure our SUT has a fresh
collaborator every time, ignorant of what happened in earlier tests.

==== First test

Let us write out first test: Make sure the machine does not return any ball(s)
when it's state is `NO_COIN`. From the <<state_diagram, State diagram>> we learn that the action
`draw()` should only be effective in the state `HAS_COIN`. This gives the
interaction, modelled in the sequence diagram below.

[[sequence_draw]]
.sequence diagram of draw
image::{topics}/images/seq_draw.svg[Draw]

As can be seen in the sequence diagram, the `dispense()` call is only allowed in
the state `HAS_COIN`, not in `NO_COIN`. Let the test `verify` that using a mockito
verify. A Mockito `verify` is similar to a JUnit `assertXXX`, it will complain (in Java:
throw an Assert Exception), when the right things are NOT happening.

[[First-Test]]
.first test
[source,java]
----
include::{testsourcedir}/olifantysballs/StateEnumTest.java[lines=63..76]
----

<1> Select the appropriate instance of the SUT.
<2> Invoke the interaction
<3> Capture the response
<4> JUnit assert the appropriate response
<5> Ensure no state change happened (we are still looking at `NO_COIN`), using a Mockito `verify(...)`.
<6> and
<7> Verify that the `dispense()` method is not called.

==== And then some

Work through the remainder of the tests.

 * `test_no_quarter_draws_nothing()` Verify that `dispense()` is _NOT_ called and state is not changed.
 * `test_one_coin_dispenses_ball()` Verify that `dispense()` is called and state is changed to `NO_COIN`.
 * `test_WINNER_dispenses_ball()` Verify that WINNER dispenses a ball and leaves the machine empty.
 * `test_one_draw_to_WINNER()` Verify that the guard `isWINNER() == true` leads to state `WINNER` and that there is also a `dispense()` call.
 * `test_WINNER_takes_all()` WINNER will take last ball. (Guess).
 * `test_WINNER_not_so_gready()` WINNER leaves a ball. (Guess).
 * `test_one_ball_to_sold_out()` Make sure that `isEmpty()` is called and next state is `SOLD_OUT` when `isEmpty()` returns `true`.
 * `insert_no_coin_to_has_coin()` Does inserting a coin have the proper effect?
 * `eject_has_coin_to_no_coin()` Does ejecting the coin have the proper effect?
 * `refill_back_to_business()` Does refill make the machine 'ready to rock'?
 * `fill_it_up_in_every_state()` What happens when you refill in all states. Make sure only `SOLD_OUT` changes state to `NO_COIN`
    and that in all other cases the state of the context is 'unaffected'.
 * `testValues()` To see if all states are there. (Coverage)
 * `testValueOf()` Ih the name translation works.  (Coverage)

==== Integrate with the real Context, the `OlifantysBallMachine`

There are big advantages by using `enum` as a state implementation:

* There is no chance of creating a new state. Enum ensures that the only
  instances there ever will be are created at class loading time.
* The instances can be shared between contexts, because the States do no have any
  state. The state is saved in the context, remember. This is not because enums
  cannot have state, they can, but because a state in a state-machine shouldn't.
  It IS the state and should not have any. More importantly, they are immutable,
  meaning no one can break them and set the State into some wrong state.
* The state is easily tested without a need for a complex context.
  It can easily be mocked as we have seen in the earlier test.

Of course, by just testing the states, we are not yet done. We must also test the
context and see if that uses the states properly and as intended.

As an example we code one of the more interesting use cases is:
_When I insert a coin in any state, ensure that only state NO_COIN leads to a new State (HAS_COIN)._

In this test we use Mockito once more, now not just to mock things, but to *spy* instead.
The whole setup and testing can take place in one test method.

[[insert_to_no_coin]]
.spying on a context
[source,java]
----
include::{testsourcedir}/olifantysballs/OlifantysBallMachineTest.java[lines=67..82]
----
<1> First we make SUT instance, then 'bug' it, as in give it to a *spy* to do its thing with it. Now we interact with the SUT _through_ the spy in
<2> insert a coin
<3> and again
<4> which should only result in one state change,
<5> namely in this state. (You could argue that this `assertSame(...)` is redundant
and you would be right. Here I do this to show that spying supports both _invocation verification_ as well as the _normal JUnit stuff_.)

==== A state machine should ignore event/methods

Looking at the <<StateTable>>, we see a lot of method method calls that do not
result in a state change (all the empty cells in the End state column). It looks
a tedious job to write all these tests, but we might be able to use a Java 8
trick here: Why not pass in all methods as method references that should be
ignored to a helper inside the test class.

Writing this helper is trivial. We know nothing about how the methods work, so
why not take the simplest Functional interface of all as their template,
`Runnable`.

The helper would now look like this:

[[no_state_change_helper]]
.helper, ensuring no state changes happened in with the given actions
[source,java]
----
include::{testsourcedir}/olifantysballs/OlifantysBallMachineTest.java[lines=205..214]
----

and used like this

[[WINNER_ignores]]
.using the method above with three actions, insert, eject and refill.
[source,java]
----
include::{testsourcedir}/olifantysballs/OlifantysBallMachineTest.java[lines=162..175]
----
where

<1> Tells the spy what to spy on
<2> which is passed as the context, as in the spy impersonates the context.
<3> is simply passing the method reference because it fits the `Runnable` function shape, so does
<4> and
<5> wraps the method call in a wrapper with a Lambda taking nothing and
returning nothing, same as `Runnable` does.

==== How about coverage

Test Driven, is that sufficient?

After completing the initial implementation, let us look at some other qualities
of our code and tests.

We use maven in 2019,
so we will demo with the maven coverage plugin, which is already in the project by virtue of
*sebipom*.


Coverage means: did we test all there is to test? Is there some uncharted code,
not tested? This is particularly bad in code that should model or implement
behaviour. Let us make sure we tested at least all we have in our `enum` and
maybe `interface` (if it has implementations, which is possible since Java 8)
in the State hierarchy too.

==== Design issues.

The initial design suggests to use interfaces both for the context (the
automaton or state machine proper) and the state. Doing this may result in
too big an API, because it exposes methods about state handling, which never should
be accessible by the client application, outside the package.

What can we do?

* Make the State package private (a.k.a. default visibility).
* Make sure that the State does not occur as parameter or return value in
`public` methods of the state machine. Since we started with the context
design as an interface, we must do better.
** Collapse the hierarchy, make enum (`private`) inner of state machine?
** What is the effect on the methods (example cheating `isWINNER()`).


==== Design Solution 1

We can solve this by making the Context into an `abstract class`,
which gives more control over the method's visibility than an `interface` does.
You can then take out all methods that should not have relevance to any client of this
implementation. You can also make `State`-interface package private and make sure
that the state objects are not leaked in or out of the package (No `protected` or
`public` on methods that have State as parameter or return type).


==== Design Solution 2.

Separate the *Device* from the public API.
The device or Context is what the states need to do their work. It can be an interface or an abstract class
but package private. The methods that are in the public API are in the other interface.

The machine implements both interfaces: the device, which is package private, to have the state interact with, so the
methods in the state can work the device to e.g. dispense a ball or refill.

The public API is a public interface and can be used by the client. There is a static factory method in the API interface That
returns an instance of an API implementing class. The rest can stay inside the `gumballmachine`  package and therefor private

'''
