CSSDIR=../css
IMAGESDIR=../images
include ../Makefile.macros

all: tdd.html winmake.html \
	restassured.html lambdaandfunctions.html lambdastreams.html

# havingaball.html: havingaball.adoc \
# 	solution/olifantysballs/test/olifantysballs/OlifantysBallMachineTest.java \
# 	solution/olifantysballs/test/olifantysballs/StateEnumTest.java

kaos.html: kaos.adoc

fraction.html: fraction.adoc

tdd.html: tdd.adoc

lambdaandfunctions.html: lambdaandfunctions.adoc

restassured.html: restassured.adoc

lambdastreams.html: lambdastreams.adoc

clean:
	rm -f *.html
