
[big]#Reclection or class introspection is used to leverage the infomation that is avialable in classes. Using the information that is
available about a class and by implication about the instances of the class can help to avoid _copy-and-waste_ programming.
It helps keeping the code https://en.wikipedia.org/wiki/Don%27t_repeat_yourself[DRY]#


== Reflection

Reflection is a multi-edged tool.

* Reflection can be used to access parts of instances that would otherwise not be available.
* Reflection can be used to list information about fields, methods, and constructors.
* Access via reflection is slower than regular access, because of the safety/security checks that are made on each access
* It is also slow for the extra indirection needed to do the work when compared
  to the optimized instructions for say access a field.
* It is [red]*less type-safe*, so you loose much of the comfort you have in the IDE, such as code-completion or intellisense(tm).
** For instance you lookup a method by name (a String) and that makes you deal with at least one exception. This still does not produce
   the actual method, but instead a [blue]#Method# object which you must give the reference to the object on which you want to apply the method and the parameters
   to that method in an `Object[]` array.

Some of the problems can be mitigated a little with the proper amount of smartness, in particular caching previous results,
and also by using `MethodHandle` in the java.lang.invoke package introduced in Java 7.

Things that can be done using reflection is building access templates to read
and write plain old java objects, typically entity classes, without having to copy and paste a lot of
similar code.
This, and code generation, is the approach that some frameworks use to reduce the
amount of boilerplate or copy and paste code that needs to be written.

We will be doing all of that in this part.
