=== Password Validator

Whenever you register an account somewhere, you are asked to create a password. Usually, this
password needs to adhere to a certain standard such as a minimum of eight characters or at least one uppercase
letter, a special character such as ampersand (&), star (*), dash (-) or exclamation marks (!).

In this exercise, you have to write methods that validate a password. For example, one
method checks whether the password contains an uppercase letter. Remember to start writing
the tests first! The password should follow these rules:

- be at least 10 characters long
- contain at least one uppercase character
- contain at least one lowercase character
- contain at least one digit
- contain at least one special character
- must not be empty

The java Character class has quite a few `static` methods to check if a character classifies as a certain kind of character. For instance
`Character.isDigit('9')`  will return `true` as will  `Character.isUpper('Ä')`.


[NOTE.extra,caption="Extra Challenge"]
====
There is also the `static` method `int getType(int codePoint)`, which may be helpful to ease your work.
Make a map of Integer to AtomicInteger and count the types that a password has. The types that you are after are UPPERCASE_LETTER,
LOWERCASE_LETTER, DECIMAL_DIGIT_NUMBER, and OTHER_PUNCTUATION,  END_PUNCTUATION,	CURRENCY_SYMBOL. So after you have put all your chars in the map,
Check the counts for each category. Upper and, lower and digit need to be at least one, and all the other characters can be counted as special.
See the Java doc for more information. Remember, learning to really on being able to browse efficiently through javadoc will be very beneficial during
the performance assessment, because it will be available there too.
====

When the password is empty, you should throw an IllegalArgumentException. Make sure that your tests test that this
exception is thrown.

[NOTE.extra,caption="Extra Challenge"]
====
Instead of an IllegalArgumentException, create your own exception and have it thrown and tested.
For example a MissingDigitException or a PasswordMustNotBeEmptyException.
====

Use a tabular test (CsvSource in Junit 5) to make up your test data.
Make sure you have a csv test line for each of the failure cases.
